---
env:
  path:
    root: "exp"
    name: "xr_pna"
    client: "/home/brandon/tfcaidm-pkg/configs/ymls/xr_pna/client.yml"
  lib:
    # pytorch: ["pytorch", "1.9.0"]
model:
  model: ["unet", "unet++", "unet3+"]
  conv_type: ["conv"]
  pool_type: ["conv"]
  eblock: ["conv"]
  elayer: [1]
  dblock: ["conv"]
  depth: [4]
  width: [32]
  width_scaling: [1]
  kernel_size: [[1, 3, 3]]
  strides: [[1, 2, 2]]
  bneck: [2]
  branches: [4]
  atrous_rate: [6]
  order: ["rnc"]
  norm: ["bnorm"]
  activ: ["leaky"]
  attn_msk: ["softmax"]
train:
  xs:
    dat:
  ys:
    pna:
      mask:
        name: ["msk"]
        remove_bg: [True]
        mask_weight: [1]
        output_weight: [5]
      head: ["decoder_classifier", "decoder_multi_scale_classifier", "decoder_deep_supervision_classifier", "decoder_complex_supervision_classifier"]
      n_classes: [2]
      loss: ["sce"]
      metric: ["dice"]
  trainer:
    seed: [0]
    n_folds: [1]
    batch_size: [8]
    iters: [10000]
    steps: [1000]
    valid_freq: [10]
    lr: [3e-4]
    lr_alpha: [0.25] # range [0, 1]
    lr_decay: [0.97] # range (0, 1]
    callbacks: [["checkpoint", "lr_scheduler", "tensorboard"]]
