---
env:
  path:
    root: "exp"
    name: "covid_biomarker"
    client: "/home/brandon/tfcaidm-pkg/configs/ymls/covid_biomarker/client.yml"
  lib:
    # pytorch: ["pytorch", "1.9.0"]
model:
  model: ["unet"]
  conv_type: ["conv"]
  pool_type: ["conv"]
  eblock:
    [
      "conv",
      "aspp",
      "cbam",
      "csp",
      "dense",
      "eca",
      "inception",
      "psp",
      "se",
      "u2net",
    ]
  elayer: [1]
  dblock: ["conv"] #, "attention", "convgru"]
  depth: [5]
  width: [8]
  width_scaling: [2]
  kernel_size: [[1, 3, 3]]
  strides: [[1, 2, 2]]
  bneck: [2]
  branches: [4]
  order: ["rnc"]
  norm: ["bnorm"]
  activ: ["leaky"]
  attn_msk: ["softmax"]
train:
  xs:
    dat:
  ys:
    pna:
      mask:
        name: ["msk-pna"]
        remove_bg: [True]
        mask_weight: [1]
        output_weight: [5]
      head: ["decoder_classifier"]
      n_classes: [2]
      loss: ["sce"]
      metric: ["dice"]
    ratio:
      mask:
        name: ["msk-ratio"]
        remove_bg: [True]
        mask_weight: [1]
        output_weight: [1]
      head: ["encoder_classifier"]
      n_classes: [1]
      loss: ["sce"]
      metric: ["mae"]
  trainer:
    seed: [0]
    n_folds: [1]
    batch_size: [8]
    iters: [10] #[10000]
    steps: [10] #[1000]
    valid_freq: [2]
    lr: [6e-3]
    lr_alpha: [0.25] # range [0, 1]
    lr_decay: [0.97] # range (0, 1]
    callbacks: [["checkpoint", "lr_scheduler", "tensorboard"]]
